export enum RouteType {
    SPLASH = 'splashScreen',
    HOME_SCREEN = 'homeScreen',
    LEGAL = 'legal',
    BACKUPWALLET = 'backupwallet',
    SEEDPHRASE = 'seedphrase',
    SUCCESS = 'success',
    LOGIN = 'login',
    WALLETBALANCE = 'walletbalance',
    SETTINGS = 'settings',
    ADDADDRESS = 'addAddress',
    ADDCOIN = 'addCoin',
    NETWORK = 'Network',
    CURRENCY = 'Currency',
    CMS = 'Cms',
    UPDATEPASSWORD = 'Update Password',
    BACKUPYOURWALLET = 'Backup Wallet',
    COPYSEEDPHRASE = 'CopySeedPhrase',
    RESTOREASSETS = 'Restore Assets',
    ASSETDETAILS = 'AssetDetails',
    RESETWALLET = 'Reset Wallet',
    SEND = 'Send',
    SENDCONFIRMATION = 'SendConfirmation',
    EDITCONFIRMATION = 'EditConfirmation',
    CONFIRMATION = 'Confirmation',
    EDITNONCE = 'Edit Nonce',
    EDITFEES = 'Edit Fees',
    BUY = 'Buy',
    INCRIPTIONDETAILS = 'InscriptionDetails',
    SENDORDINALS = 'SendOrdinals',
    TRANSFER = 'Transfer',
    FORGOTPASSWORD = 'ForgotPassword',
    RECEIVE = 'Receive',
    VIEWQR = 'ViewQr',
    WARNING = 'Warning',
    WALLETRESTORED='WalletRestored',
    RESETWALLETPASSWORD='ResetWalletPassword',
    SENDORDINALSCONFIRMATION='SendORdinalsConfirmation',
    CONFIRMBRC20='ConfirmBrc20',
    SENDCONFIRMBRC20='SendConfirmBrc20',
    BORROW='Borrow',
    BORROWOFFERS='BorrowOffers',
    BORROWCONFIRMATION='BorrowConfirmation',
    LOANSTATUS='LoanStatus',
    SWAP='SWAP',
    SWAPPROVIDERS='SwapProviders',
    SWAPDETAILS='SwapDetails',
    REVIEWSWAPTRANSACTION='ReviewSwapTransaction',
    CONFIRMSWAPTRANSACTION='ConfirmSwapTransaction',
    REPAY='Repay',
    

  }
  