
const localAssets = {
  // Images
  icShow: require('./images/show.png'),
  icHide: require('./images/hide.png'),
  apple: require('./images/apple.png'),
  discord: require('./images/discord.png'),
  facebook: require('./images/facebook.png'),
  twitter: require('./images/twitter.png'),
  appLogo: require('./images/logo.png'),

  pill: require('./images/pill.png'),
  pin: require('./images/pin.png'),
  key: require('./images/key.png'),
  backicon: require('./images/backicon.png'),
  lock: require('./images/lock.png'),
  eye: require('./images/eye.png'),
  eyeoff: require('./images/eyeoff.png'),

  congratulation: require('./images/congratulation.png'),
  selfcustody: require('./images/selfcustody.png'),
  anonymus: require('./images/anonymus.png'),
  private: require('./images/private.png'),
  decentralized_success: require('./images/decentralized.png'),

  bottomwallet: require('./images/bottomwallet.png'),
  marketbottom: require('./images/marketbottom.png'),
  bottomnft: require('./images/bottomnft.png'),
  bottomassitant: require('./images/bottomassitant.png'),

  copy: require('./images/copy.png'),
  qr: require('./images/qr.png'),
  settings: require('./images/settings.png'),

  walletbg: require('./images/walletbg.png'),
  walletbalance: require('./images/balancewallet.png'),
  orangetransaction: require('./images/orangetransaction.png'),
  addcoin: require('./images/addcoin.png'),

  downarrow: require('./images/downarrow.png'),
  nftwallet: require('./images/nftwallet.png'),

  transferarrow: require('./images/transferarrow.png'),
  transactionarrow: require('./images/transactionarrow.png'),
  samplenft: require('./images/samplenft.png'),
  bitcoinicon: require('./images/bitcoinicon.png'),
  assetbitcoin: require('./images/assetbitcoin.png'),
  receive: require('./images/receive.png'),
  sell: require('./images/sell.png'),
  buy: require('./images/buy.png'),
  send: require('./images/send.png'),
  bitcoincard: require('./images/bitcoincard.png'),
  dropdownarrow: require('./images/dropdownarrow.png'),
  incriptionsample: require('./images/incriptionsample.png'),
  nftordinals: require('./images/nftordinals.png'),
  transactioncrypto1: require('./images/transactioncrypto1.png'),
  transactioncrypto2: require('./images/transactioncrypto2.png'),
  transactionvector: require('./images/transactionvector.png'),
  transactionsending: require('./images/sending.png'),
  transactiondone: require('./images/done.png'),
  qrcodesample: require('./images/qrcodesample.png'),
  whitecross: require('./images/whitecross.png'),
  yellowcross: require('./images/toastclose.png'),
  toastright: require('./images/toastright.png'),
  stackscard: require('./images/stackscard.png'),
  contract: require('./images/contract.png'),
  pendingIcon: require('./images/pendingIcon.png'),
  failed: require('./images/failed.png'),

  // Cypto Icons

  RATS: require('./images/RATS.png'),
  RSIC: require('./images/RSIC.png'),
  WAM: require('./images/WAM.png'),
  UNCOMMONGOODS: require('./images/UNCOMMON•GOODS.png'),
  Decentralized: require('./images/Decentralized.png'),
  WrappedUSDC: require('./images/Wrapped USDC.png'),
  ARKADIKO: require('./images/ARKADIKO.png'),
  LEO: require('./images/LEO.png'),
  BRC20: require('./images/BRC20.png'),
  Unisat: require('./images/Unisat.png'),
  OKX: require('./images/OKX.png'),
  Leather: require('./images/Leather.png'),
  XVerse: require('./images/XVerse.png'),
  Welshcorgi: require('./images/Welshcorgi.png'),
  DOG: require('./images/DOG.png'),
  SATOSHINAKAMOTO: require('./images/SATOSHI•NAKAMOTO.png'),
  BTC: require('./images/BTC.png'),
  WANKOMANKO: require('./images/WANKOMANKO.png'),
  PUPSWORLDPEACE: require('./images/PUPS•WORLD•PEACE.png'),
  TRAC: require('./images/TRAC.png'),
  Base: require('./images/Base.png'),
  Linea: require('./images/Linea.png'),
  MagicEden: require('./images/MagicEden.png'),
  Multibit: require('./images/Multibit.png'),
  WrappedBitcoin: require('./images/Wrapped Bitcoin.png'),
  WrappedUSDT: require('./images/Wrapped USDT.png'),
  Orange: require('./images/Orange.png'),
  Stacks: require('./images/Stacks.png'),
  Bitcoin: require('./images/Bitcoin.png'),
  PolygonMatic: require('./images/Polygon Matic.png'),
  BNBChain: require('./images/BNB Chain.png'),
  Ethereum: require('./images/Ethereum.png'),
  Alexgo: require('./images/Alexgo.png'),
  ORDI: require('./images/ORDI.png'),
  SATS: require('./images/SATS.png'),


  RATSOrange: require('./images/RATSOrange.png'),
  RSICOrange: require('./images/RSICOrange.png'),
  WAMOrange: require('./images/WAMOrange.png'),
  UNCOMMONGOODSOrange: require('./images/UNCOMMON•GOODSOrange.png'),
  DecentralizedOrange: require('./images/DecentralizedOrange.png'),
  WrappedUSDCOrange: require('./images/Wrapped USDCOrange.png'),
  ARKADIKOOrange: require('./images/ARKADIKOOrange.png'),
  LEOOrange: require('./images/LEOOrange.png'),
  BRC20Orange: require('./images/BRC20Orange.png'),
  UnisatOrange: require('./images/UnisatOrange.png'),
  OKXOrange: require('./images/OKXOrange.png'),
  LeatherOrange: require('./images/LeatherOrange.png'),
  XVerseOrange: require('./images/XVerseOrange.png'),
  WelshcorgiOrange: require('./images/WelshcorgiOrange.png'),
  DOGOrange: require('./images/DOGOrange.png'),
  SATOSHINAKAMOTOOrange: require('./images/SATOSHI•NAKAMOTOOrange.png'),
  BTCOrange: require('./images/BTCOrange.png'),
  WANKOMANKOOrange: require('./images/WANKOMANKOOrange.png'),
  PUPSWORLDPEACEOrange: require('./images/PUPS•WORLD•PEACEOrange.png'),
  TRACOrange: require('./images/TRACOrange.png'),
  BaseOrange: require('./images/BaseOrange.png'),
  LineaOrange: require('./images/LineaOrange.png'),
  MagicEdenOrange: require('./images/MagicEdenOrange.png'),
  MultibitOrange: require('./images/MultibitOrange.png'),
  WrappedBitcoinOrange: require('./images/Wrapped BitcoinOrange.png'),
  WrappedUSDTOrange: require('./images/Wrapped USDTOrange.png'),
  OrangeOrange: require('./images/OrangeOrange.png'),
  StacksOrange: require('./images/StacksOrange.png'),
  BitcoinOrange: require('./images/BitcoinOrange.png'),
  PolygonMaticOrange: require('./images/Polygon MaticOrange.png'),
  BNBChainOrange: require('./images/BNB ChainOrange.png'),
  EthereumOrange: require('./images/EthereumOrange.png'),
  AlexgoOrange: require('./images/AlexgoOrange.png'),
  ORDIOrange: require('./images/ORDIOrange.png'),
  SATSOrange: require('./images/SATSOrange.png'),
  nft: require('./images/nft.png'),
  dropupArrow: require('./images/dropupArrow.png'),
  

};
// Exporting IMAGES
export {
  localAssets,
};
